### ISSUE TITLE
pip installed version doesn't contain chosen js and css files.

### ISSUE THREAD

**Issue by donvito-pl** [bradmontgomery/django-chosenadmin#1]
Exception Type: TemplateDoesNotExist
Exception Value:    chosenadmin/css/chosen.min.css

ls -1 /usr/local/lib/python2.7/dist-packages/chosenadmin   yields:
**init**.py
**init**.pyc
middleware.py
middleware.pyc

Worth mentioning in README file.

**Comment by bradmontgomery** [comment]
This seems like a bug. I'd expect that when you run `collectstatic` you should get those files. I've probably left something out of `setup.py` :-/

Will investigate and try to resolve later today.

**Comment by donvito-pl** [comment]
I was expecting the same, but collectstatic wasn't able to find these files.
I had to git clone them manually into my project and then the whole thing started to work.

This solution is simple to setup, but unfortunately admin pages get quite messy and some extra css work is required. 

Maybe extra styling from Radtek will work (I haven't tried them yet):
http://stackoverflow.com/questions/8735657/trouble-getting-django-chosen-chosenselect-widget-to-work/25951053#25951053

Thank You.

**Comment by bradmontgomery** [comment]
Just pip-installed this from the git repo, ran collectstatic, and my admin site had the css, js, and images. New version should hit pypi soon.

Thanks for reporting @donvito-pl
